var facts = ["CATS SPEND BETWEEN 30 TO 50 PERCENT OF THEIR DAY GROOMING THEMSELVES.",
"IT'S POSSIBLE THAT PURRING HELPS BONE DENSITY.",
"A CAT'S NOSE HAS CATNIP RECEPTORS.",
"CATS MAKE GREAT PRIVATE DETECTIVES.",
"THE WEALTHIEST CAT IS NAMED BLACKIE.",
"YOUR CAT PROBABLY HATES MUSIC.",
"MANY HISTORICAL FIGURES LOVED CATS.",
"IF YOU LOVE CATS, YOU'RE AN AILUROPHILE.",
"CATS FIRST WENT TO SPACE IN 1963.",
"THE WORLD'S OLDEST LIVING CAT IS 31 YEARS OLD.",
"THE GUINNESS WORLD RECORDS DON'T HAVE AN AWARD FOR FATTEST CAT.",
"CATS MIGHT BE MARKING YOU AS TERRITORY WHEN THEY MASSAGE YOU.",
"THERE'S A CAT PAINTING WORTH CLOSE TO $1 MILLION.",
"YOUR CAT MIGHT BE ALLERGIC TO YOU.",
"CATS CAN'T TASTE SWEETS."];

function showRandomFact(){
var randomNumber = Math.floor(Math.random() * (facts.length));
var randomFact = facts[randomNumber];
document.getElementById("text").innerHTML = randomFact;
}